spring:
  datasource:
    hikari:
      username: root
      password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/test?serverTimezone=UTC
  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    show-sql: true
    hibernate:
      ddl-auto: update
  redis:
    cluster:
      nodes:
         - 192.168.11.129:7001
         - 192.168.11.129:7002
         - 192.168.11.129:7003
         - 192.168.11.129:7004
         - 192.168.11.129:7005
         - 192.168.11.129:7006
      max-redirects: 3

server:
  port: 8080